apiVersion: v1
kind: Service
metadata:
  name: airlab-app-service
  namespace: airlab-namespace
spec:
  selector:
    app: airlab-app
  ports:
    - port: 80
      targetPort: 5000
      name: http
  type: NodePort
