apiVersion: apps/v1
kind: Deployment
metadata:
  name: airlab-app
  namespace: airlab-namespace
spec:
  replicas: 
  selector:
    matchLabels:
      app: airlab-app
  template:
    metadata:
      labels:
        app: airlab-app
    spec:
      containers:
        - name: airlab-app
          image: airlab-app-image:1.2
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 5000
          env:
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: airlab-secret
                  key: api_key
            - name: BASE_API_URL
              value: "https://open-atms.airlab.aero/api/v1/"
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 5000
            initialDelaySeconds: 10    # Delay before the first probe
            periodSeconds: 30          # Interval between probes              
