apiVersion: v1
kind: Service
metadata:
  name: airlab-app-service
  namespace: airlab-namespace
spec:
  selector:
    app: airlab-app
  ports:
    - protocol: "TCP"
      port: 8000
      targetPort: 8000
  type: NodePort
