name: Build docker image and push to Minikube repository

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push-local-windows:
    runs-on: [self-hosted, Windows]  # Use the self-hosted runner which is on Powershell
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Build Docker Image on Windows Locally
        run: |
          # Configure Docker to use the Minikube Docker daemon
          minikube docker-env | Invoke-Expression

          # Build Docker image
          docker build -t airlab-app-image:${{ github.sha }} .
        working-directory: App/
          
      - name: Push Docker Image to Minikube Registry
        run: |
          # Deploy deployment file
          kubectl apply -f airlab-deployment.yaml
          kubectl set image deployment/airlab-app airlab-app=airlab-app-image:${{ github.sha }}

          # Deploy service file
          kubectl apply -f airlab-service.yaml
        working-directory: Infra/

      # TODO: Consider run test case to verify service is good         

  build-and-push-local-mac:
    runs-on: [self-hosted, macOS]  # Use the self-hosted runner which is on MacOS
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
    
      # We assume minikube and docker engine is started
      - name: Build Docker Image on MacOS Locally
        run: |
          # Configure Docker to use the Minikube Docker daemon
          eval $(minikube -p minikube docker-env)  

          # Build Docker image
          docker build -t airlab-app-image:${{ github.sha }} .
          #docker tag airlab-app-image:latest minikube/airlab-app-image:${{ github.sha }}
        working-directory: App/

      - name: Deploy Kubectl deployment and services
        run: |            
          # Deploy deployment file
          kubectl apply -f airlab-deployment.yaml
          kubectl set image deployment/airlab-app airlab-app=airlab-app-image:${{ github.sha }}

          # Deploy service file
          kubectl apply -f airlab-service.yaml
        working-directory: Infra/

      # TODO: Consider run test case to verify service is good        
