name: Build docker image and push to Minikube repository

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push-local-windows:
    runs-on: [self-hosted, Windows]  # Use the self-hosted runner which is on Powershell
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      # TODO: Consider run test case here
      # We assume minikube is started      

      - name: Configure Docker to Use Minikube Registry
        run: |
          # Configure Docker to use the Minikube Docker daemon
          minikube docker-env | Invoke-Expression

      - name: Build Docker Image on Windows Locally
        run: |
          # Build Docker image
          docker build -t airlab-app-image:latest .
        working-directory: C:\Users\gapch\Desktop\Dev\airlab-atms-program\App\
          
      - name: Push Docker Image to Minikube Registry
        run: |
          # Push the Docker image to the Minikube Docker registry
          docker push airlab-app-image:latest

  build-and-push-local-mac:
    runs-on: [self-hosted, macOS]  # Use the self-hosted runner which is on MacOS
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
    
      # TODO: Consider run test case here
      # We assume minikube is started

      - name: Configure Docker to Use Minikube Registry
        run: |
          # Configure Docker to use the Minikube Docker daemon
          eval $(minikube -p minikube docker-env)     

      - name: Build Docker Image on MacOS Locally
        run: |
          pwd
          ls -ltr        
          # Build Docker image
          docker build -t airlab-app-image:latest .
          docker tag airlab-app-image:latest minikube/airlab-app-image:latest
        working-directory: Apps/

      - name: Deploy Kubectl deployment and services
        run: |
          pwd
          ls -ltr             
          # Deploy deployment file
          kubectl apply -f airlab-deployment.yaml

          # Deploy service file
          kubectl apply -f airlab-service.yaml

          # Run minikube tunnel to airlab-app-service
          minikube service airlab-app-service -n airlab-namespace
        working-directory: Infra/
               
      # Update Kubernetes file to use latest image
      # Update service, if needed


